(()=>{'use strict';
function start(){const old=document.querySelector('.dashboard-landing .tool-selector');if(!old||!window.RvisioonDemo)return;old.hidden=true;
const data=[['Métricas','COMPRENDER','Mide el interés. Encuentra oportunidades.','Consulta visitas, prospectos y unidades reservadas. Reconoce las tendencias que ayudan a tu equipo a enfocar su atención.','Visitas · Prospectos · Tendencias · Filtros de fecha','metrics'],['Disponibilidad','ADMINISTRAR','Cada unidad, con su estado al día.','Visualiza qué unidades están disponibles, reservadas o vendidas y mantén el contexto del proyecto al alcance de tu equipo.','Unidades · Estados · Disponibilidad','units'],['Creación de contenido','CREAR','De tus recursos a nuevas piezas.','Organiza las imágenes del proyecto y prepara contenido para acompañar cada etapa de la comunicación comercial.','Galerías · Multimedia · Brochure · Recursos','content']];
const selector=document.createElement('div');selector.className='skill-selector';selector.setAttribute('role','group');selector.setAttribute('aria-label','Funcionalidades del dashboard');selector.innerHTML=data.map((d,i)=>`<button type="button" data-skill="${i}" aria-pressed="${i===0}"><small>0${i+1}</small>${d[0]}</button>`).join('');old.after(selector);
const preview=document.querySelector('.feature-preview');document.querySelector('#tool-image').hidden=true;document.querySelector('.capture-zoom').hidden=true;preview.hidden=false;
function render(i){const d=data[i];['tool-label','tool-title','tool-copy','tool-detail'].forEach((id,n)=>document.getElementById(id).textContent=d[n+1]);selector.querySelectorAll('button').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-pressed',String(n===i))});preview.replaceChildren(window.RvisioonDemo(d[5]));document.querySelector('#tool-source').textContent='Demostración animada · Datos y acciones ilustrativos';}
selector.querySelectorAll('button').forEach((b,i)=>b.addEventListener('click',()=>render(i)));render(0);}
if(window.RvisioonDemo)start();else addEventListener('rvisioon-demo-ready',start,{once:true});
})();
