(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion: reduce)'),clamp=x=>Math.max(0,Math.min(1,x)),ease=x=>{x=clamp(x);return x*x*(3-2*x)};
const range=document.querySelector('#construction-range');
if(range){const sec=range.closest('section'),scene=sec.querySelector('.build-comparison'),out=sec.querySelector('#construction-month');let frame;
 const render=()=>{const p=+range.value/120,month=Math.round(p*12),label=p<.25?'El punto de partida':p<.75?'El proyecto toma forma':'Un lugar para vivir';scene.style.setProperty('--building',ease(p*2));scene.style.setProperty('--finished',ease((p-.5)*2));out.replaceChildren(document.createTextNode('Mes '+String(month).padStart(2,'0')+' '));const small=document.createElement('small');small.textContent='/ '+label;out.append(small);range.setAttribute('aria-valuetext','Mes '+month+', '+label+'. Secuencia ilustrativa');sec.querySelectorAll('[data-month]').forEach(b=>b.setAttribute('aria-pressed',String(+b.dataset.month===(p<.25?0:p<.75?60:120))));};
 range.addEventListener('input',()=>{cancelAnimationFrame(frame);render()});sec.querySelectorAll('[data-month]').forEach(b=>b.addEventListener('click',()=>{cancelAnimationFrame(frame);const from=+range.value,to=+b.dataset.month,start=performance.now();const tick=now=>{const p=reduced.matches?1:clamp((now-start)/900);range.value=from+(to-from)*ease(p);render();if(p<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick)}));render();}
const journey=document.querySelector('.immersive-journey');if(!journey)return;
const pin=journey.querySelector('.immersive-pin'),stage=journey.querySelector('.portal-stage'),canvas=journey.querySelector('canvas'),ctx=canvas.getContext('2d'),video=journey.querySelector('video'),pause=journey.querySelector('.portal-motion'),steps=[...journey.querySelectorAll('[data-portal-step]')];
let progress=0,manual=null,stopped=false,inView=false,raf=0,last=0,travel=0,mouseX=0,mouseY=0,targetX=0,targetY=0,w=0,h=0,chapter=-1;
const points=Array.from({length:110},(_,i)=>({angle:i*2.399963,depth:((i*37)%109)/109,radius:.25+((i*17)%47)/47*.75,size:i%5===0?1.7:.8}));
const set=(k,v)=>journey.style.setProperty(k,v);
function size(){w=stage.clientWidth;h=stage.clientHeight;const d=Math.min(devicePixelRatio||1,1.5);canvas.width=w*d;canvas.height=h*d;ctx?.setTransform(d,0,0,d,0,0);render();}
function render(){const p=progress,fit=Math.max(w/1672,h/941),cx=w/2,cy=(h-941*fit)*.28+260*fit,zoom=ease((p-.06)/.64),scale=1+zoom*5.8,expansion=ease((p-.32)/.4),halfW=181*fit*scale,halfH=78*fit*scale;
 set('--portal-origin',cx+'px '+cy+'px');set('--portal-scale',scale);set('--subject-opacity',1-ease((p-.57)/.15));set('--world-opacity',ease((p-.09)/.13));set('--portal-side',Math.max(0,(cx-halfW)/w*100)*(1-expansion)+'%');set('--portal-top',Math.max(0,(cy-halfH)/h*100)*(1-expansion)+'%');set('--portal-bottom',Math.max(0,(h-cy-halfH)/h*100)*(1-expansion)+'%');set('--portal-round',(32*(1-expansion))+'px');set('--world-scale',1.18-.15*ease((p-.45)/.5));set('--intro-opacity',1-ease((p-.12)/.2));set('--intro-y',(-50*ease(p/.35))+'px');set('--destination-opacity',ease((p-.73)/.16));set('--portal-progress',(p*100)+'%');set('--portal-flash',Math.sin(clamp((p-.44)/.25)*Math.PI)*.5);
 const n=p<.27?0:p<.72?1:2;if(n!==chapter){chapter=n;steps.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===n)));journey.querySelector('.portal-intro').setAttribute('aria-hidden',String(n!==0));journey.querySelector('.portal-destination').setAttribute('aria-hidden',String(n!==2));journey.querySelector('.portal-real-link').tabIndex=n===2?0:-1;}syncVideo();}
function syncVideo(){const play=inView&&!stopped&&!reduced.matches&&!document.hidden&&!document.body.classList.contains('paused')&&progress>.12;if(play&&video.paused)video.play().catch(()=>{});else if(!play&&!video.paused)video.pause();}
function update(){const rect=journey.getBoundingClientRect();inView=rect.top<innerHeight&&rect.bottom>0;journey.classList.toggle('in-view',rect.top<innerHeight*.6&&rect.bottom>innerHeight*.4);if(manual===null&&!stopped&&!reduced.matches)progress=clamp(-rect.top/Math.max(1,journey.offsetHeight-pin.offsetHeight));render();if(inView&&!raf&&!stopped&&!reduced.matches&&!document.hidden)raf=requestAnimationFrame(draw);}
function draw(now){raf=0;if(!inView||stopped||reduced.matches||document.hidden||document.body.classList.contains('paused')){last=0;ctx?.clearRect(0,0,w,h);return}const dt=last?Math.min(40,now-last):16;last=now;mouseX+=(targetX-mouseX)*.06;mouseY+=(targetY-mouseY)*.06;set('--mouse-x',mouseX);set('--mouse-y',mouseY);ctx?.clearRect(0,0,w,h);
 if(ctx){const intensity=Math.sin(clamp((progress-.04)/.75)*Math.PI),speed=.000015+intensity*.00022;travel+=dt*speed;const cx=w/2+mouseX*28,cy=h*.36+mouseY*18;for(const point of points){const z=(point.depth+travel)%1,r=point.radius*(.1+z*z)*Math.max(w,h)*.65,x=cx+Math.cos(point.angle)*r,y=cy+Math.sin(point.angle)*r*.65,tail=1+intensity*z*25;ctx.strokeStyle=`rgba(214,177,255,${(.08+intensity*.7)*Math.sin(z*Math.PI)})`;ctx.lineWidth=point.size*(.4+z);ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(point.angle)*tail,y+Math.sin(point.angle)*tail*.65);ctx.stroke();}}
 raf=requestAnimationFrame(draw);}
stage.parentElement.addEventListener('pointermove',e=>{const box=pin.getBoundingClientRect();targetX=(e.clientX/Math.max(1,w)-.5)*2;targetY=((e.clientY-box.top)/Math.max(1,h)-.5)*2;});pin.addEventListener('pointerleave',()=>{targetX=targetY=0});
steps.forEach((b,i)=>b.addEventListener('click',()=>{const p=[0,.49,.95][i];if(reduced.matches||stopped){manual=p;progress=p;render();}else{manual=null;scrollTo({top:scrollY+journey.getBoundingClientRect().top+p*(journey.offsetHeight-pin.offsetHeight),behavior:'instant'});update();}}));
pause.addEventListener('click',()=>{stopped=!stopped;pause.setAttribute('aria-pressed',String(stopped));pause.textContent=stopped?'Activar movimiento ▷':'Pausar movimiento Ⅱ';if(!stopped)manual=null;update()});
addEventListener('scroll',()=>{if(!stopped&&!reduced.matches)manual=null;update()},{passive:true});addEventListener('resize',size);reduced.addEventListener('change',()=>{manual=null;progress=0;update()});document.addEventListener('visibilitychange',update);new MutationObserver(update).observe(document.body,{attributes:true,attributeFilter:['class']});size();update();
const ambient=[...document.querySelectorAll('.ambient-film')];const seen=new WeakSet();const filmObserver=new IntersectionObserver(entries=>entries.forEach(e=>{const v=e.target;if(e.isIntersecting&&!seen.has(v)&&!reduced.matches&&!document.body.classList.contains('paused')){seen.add(v);v.play().catch(()=>{})}else if(!e.isIntersecting)v.pause()}),{threshold:.5});ambient.forEach(v=>filmObserver.observe(v));
})();
