(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion:reduce)'),mobile=matchMedia('(max-width:760px)'),clamp=x=>Math.max(0,Math.min(1,x));
const film=document.querySelector('.brand-film'),deck=document.querySelector('.expertise-deck'),vr=document.querySelector('.vr-journey'),tour=document.querySelector('#vr-tour-video');
let requested=false;
function update(){requested=false;const paused=document.body.classList.contains('paused');if(film){const r=film.getBoundingClientRect();const p=clamp((innerHeight*.35-r.top)/Math.max(1,film.offsetHeight-innerHeight));film.style.setProperty('--film-scale',reduced.matches||paused?1:.78+.22*p)}if(deck){const p=clamp((innerHeight*.9-deck.getBoundingClientRect().top)/(innerHeight*.5));deck.style.setProperty('--deck-progress',reduced.matches?1:p)}if(tour){const r=vr.getBoundingClientRect();const active=r.top<innerHeight*.8&&r.bottom>innerHeight*.2&&vr.dataset.chapter==='2'&&!reduced.matches&&!paused&&document.querySelector('.vr-motion').getAttribute('aria-pressed')!=='true'&&!document.hidden;if(active&&tour.paused)tour.play().catch(()=>{});else if(!active&&!tour.paused)tour.pause()}}
function schedule(){if(!requested){requested=true;requestAnimationFrame(update)}}
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.addEventListener('visibilitychange',schedule);reduced.addEventListener('change',schedule);if(vr)new MutationObserver(schedule).observe(vr,{attributes:true,attributeFilter:['data-chapter']});new MutationObserver(schedule).observe(document.body,{attributes:true,attributeFilter:['class']});document.querySelector('.vr-motion')?.addEventListener('click',schedule);
document.querySelector('.quality-motion')?.addEventListener('click',e=>{const stopped=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',stopped);e.currentTarget.textContent=stopped?'Activar movimiento ▷':'Pausar movimiento Ⅱ';document.body.classList.toggle('paused',stopped)});
update();
})();
