(()=>{'use strict';
const reduced=matchMedia('(prefers-reduced-motion:reduce)'),mobile=matchMedia('(max-width:760px)');
const pulse=el=>{if(!el||reduced.matches)return;el.classList.remove('revision-switched');void el.offsetWidth;el.classList.add('revision-switched')};
const choose=(selector,selected)=>document.querySelectorAll(selector).forEach(b=>b.setAttribute('aria-pressed',String(b===selected)));
const depth=[['showroom-proyecto.webp','Ubica el proyecto antes de entrar.','La vista general, la ubicación y el entorno ayudan a entender dónde está el proyecto y cómo se relacionan sus espacios.','Arquitectura · Ubicación · Entorno'],['showroom-planta.webp','De una planta al departamento.','El selector de plantas permite explorar las unidades y consultar sus distribuciones. En desarrollos horizontales, la navegación se organiza por zonas y etapas.','Plantas · Unidades · Planos de distribución'],['showroom-recorrido.webp','Mira los espacios desde dentro.','Los recorridos virtuales permiten explorar los interiores. Las vistas de amenidades y áreas comunes completan la presentación del proyecto.','Recorridos virtuales · Interiores · Amenidades'],['showroom-amenidades.webp','La presentación, en un solo lugar.','Imágenes, video y recursos del proyecto acompañan la exploración. El visitante encuentra información para conocer la propuesta y ponerse en contacto.','Galería · Video · Información del proyecto · Contacto']];
depth.push(['showroom-mapa-interactivo.webp','El valor también está alrededor.','Un mapa interactivo permite explorar comercios, centros educativos, servicios de salud y espacios de recreación cercanos. Los filtros por categoría y la opción de cómo llegar ayudan a presentar el valor de la zona junto al proyecto.','Mapa interactivo · Lugares cercanos · Filtros por categoría · Cómo llegar']);
document.querySelectorAll('[data-depth]').forEach(b=>b.addEventListener('click',()=>{choose('[data-depth]',b);const d=depth[Number(b.dataset.depth)];const im=document.querySelector('#depth-image');im.src='assets/'+d[0];im.alt=d[1]+' Vista real del showroom de Océano Atlántico.';['depth-title','depth-copy','depth-detail'].forEach((id,i)=>document.getElementById(id).textContent=d[i+1]);pulse(document.querySelector('.depth-view'))}));
const toolData=[
['dashboard-metricas.webp','MÉTRICAS','Conoce la actividad del showroom.','Revisa visitas, prospectos, unidades reservadas y vendedores activos por período. Explora las visitas y la permanencia por unidad, los dispositivos utilizados y las zonas más consultadas. La vista por vendedor reúne su actividad de citas y prospectos.','General · Unidades · Dispositivos · Vendedores · Filtros de fecha'],
['dashboard-agenda.webp','CALENDARIO','Cada conversación, en su lugar.','Consulta la agenda por asesor en vistas de mes, semana o día. Programa citas presenciales o virtuales con prospectos nuevos o existentes, relaciona unidades de interés y añade notas. Configura horarios y duración de atención, y coordina traspasos temporales o definitivos entre asesores.','Citas y estados · Disponibilidad · Asignación de asesores · Traspasos'],
['dashboard-recursos.webp','CONTENIDO','Del material del proyecto a tu próxima pieza.','Trabaja con diseños, plantillas y recursos de la galería para preparar contenido. El panel reúne un flujo de diseño manual y un Estudio Creativo IA, con formatos para distintas redes. Consulta piezas en borrador o completadas, descarga el resultado y reutiliza diseños como plantillas.','Diseño manual · Estudio Creativo IA · Plantillas · Formatos sociales · Descargas'],
[null,'USUARIOS','El equipo también tiene su espacio.','Consulta los usuarios registrados y añade nuevos integrantes con sus datos de acceso. Mantén identificado a quien participa en la gestión del proyecto desde el panel.','Listado del equipo · Registro de usuarios · Datos de acceso'],
[null,'UNIDADES','La información de cada unidad, organizada.','Explora las unidades por plantas, en tabla o en un tablero de estados: disponible, apartado y vendido. Consulta dormitorios, baños, área, planos, galería y brochure en la ficha de cada unidad, y gestiona su estado comercial.','Plantas · Tabla · Tablero de estados · Ficha de unidad'],
[null,'MULTIMEDIA','Encuentra el recurso para cada presentación.','Busca y consulta los archivos del proyecto por categorías. Accede a videos, imágenes de amenidades y recursos por unidad, y descarga los materiales para acompañar el trabajo comercial y de contenido.','Buscador · Categorías · Videos · Amenidades · Recursos por unidad'],
[null,'BROCHURE','La información comercial, reunida.','Organiza brochures en PDF del proyecto o de una unidad específica. Carga el archivo, identifica su título y consulta su estado desde el listado; también puedes editar o retirar un documento cuando corresponda.','PDF del proyecto · PDF por unidad · Título y estado · Gestión de documentos'],
[null,'AVANCES DE OBRA','Cuenta cómo avanza el proyecto.','Reúne imágenes y videos del avance de obra con título, mes, año y descripción. Consulta los registros en cuadrícula o lista y agrega, edita o retira contenido para mantener organizada la evolución del desarrollo.','Imágenes y videos · Mes y año · Descripciones · Cuadrícula y lista']];
const featureViews={3:['Usuarios del proyecto',['Equipo comercial','Nombre y correo','Datos de acceso'],'La gestión comienza con un equipo identificado.'],4:['Unidades del proyecto',['Disponible','Apartado','Vendido'],'Plantas / Tabla / Tablero de estados'],5:['Biblioteca multimedia',['Videos','Amenidades','Por unidad'],'Busca, consulta y descarga los recursos.'],6:['Brochures en PDF',['Proyecto','Por unidad','Título y estado'],'Información comercial organizada por documento.'],7:['Avances de obra',['Imagen o video','Mes y año','Descripción'],'Cuadrícula / Lista']};
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{choose('[data-tool]',b);const n=Number(b.dataset.tool),d=toolData[n],im=document.querySelector('#tool-image'),preview=document.querySelector('.feature-preview');im.hidden=!d[0];document.querySelector('.capture-zoom').hidden=!d[0];if(preview)preview.hidden=!!d[0];if(d[0]){im.src='assets/'+d[0];im.alt=d[2]+' Interfaz ilustrativa del dashboard.'}else if(preview){const f=featureViews[n];preview.replaceChildren();const heading=document.createElement('h4');heading.textContent=f[0];preview.append(heading);const tiles=document.createElement('div');tiles.className='feature-preview-tiles';f[1].forEach(label=>{const tile=document.createElement('span');tile.textContent=label;tiles.append(tile)});preview.append(tiles);const caption=document.createElement('p');caption.textContent=f[2];preview.append(caption)}document.querySelector('#tool-source').textContent=d[0]?'Interfaz ilustrativa · Datos simulados':'Esquema de funcionalidades · No es una captura del sistema';['tool-label','tool-title','tool-copy','tool-detail'].forEach((id,i)=>document.getElementById(id).textContent=d[i+1]);pulse(document.querySelector('.tool-story'))}));
const dialog=document.querySelector('#capture-dialog');document.querySelector('.capture-zoom')?.addEventListener('click',()=>{const im=document.querySelector('#tool-image');dialog.querySelector('img').src=im.src;dialog.querySelector('img').alt=im.alt;dialog.querySelector('p').textContent=document.querySelector('#tool-source').textContent;dialog.showModal()});document.querySelector('.capture-close')?.addEventListener('click',()=>dialog.close());dialog?.addEventListener('click',e=>{if(e.target===dialog)dialog.close()});
document.querySelectorAll('[data-perspective]').forEach(b=>b.addEventListener('click',()=>{choose('[data-perspective]',b);const team=b.dataset.perspective==='equipo';document.querySelector('.perspective-view').classList.toggle('is-team',team);document.querySelector('#perspective-image').src='assets/'+(team?'dashboard-metricas.webp':'showroom-recorrido.webp');document.querySelector('#perspective-image').alt=team?'Vista de métricas del dashboard':'Recorrido real del showroom de Océano Atlántico';document.querySelector('#perspective-label').textContent=team?'ACCESO PRIVADO / DASHBOARD':'ACCESO PÚBLICO / SHOWROOM';document.querySelector('#perspective-note').textContent=team?'Interfaz ilustrativa · Datos simulados':'Océano Atlántico · Showroom real';document.querySelector('#perspective-title').textContent=team?'La información, del lado de tu equipo.':'El proyecto, abierto a explorar.';document.querySelector('#perspective-copy').textContent=team?'Con su cuenta, el equipo consulta métricas, organiza citas y accede a los recursos del proyecto.':'El visitante conoce los espacios, consulta las opciones y encuentra cómo ponerse en contacto.';const a=document.querySelector('#perspective-link');a.href=team?'#herramientas':'showroom.html';a.textContent=team?'Explorar las herramientas ↑':'Conocer el showroom ↗';pulse(document.querySelector('.perspective-copy'))}));
const ribbon=document.querySelector('.ribbon-track');if(ribbon){[...ribbon.children].forEach(el=>{const clone=el.cloneNode(true);clone.alt='';clone.setAttribute('aria-hidden','true');ribbon.append(clone)});document.querySelector('.ribbon-toggle').addEventListener('click',e=>{const stopped=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(stopped));e.currentTarget.textContent=stopped?'Activar franja ▷':'Pausar franja Ⅱ';ribbon.closest('section').classList.toggle('is-paused',stopped)})}
document.querySelectorAll('[data-team]').forEach(d=>d.addEventListener('toggle',()=>{if(!d.open)return;document.querySelectorAll('[data-team]').forEach(other=>{if(other!==d)other.open=false});const im=document.querySelector('#team-image'),name=d.querySelector('summary').childNodes[1].textContent.trim();im.src='assets/'+d.dataset.teamImage;im.alt='Trabajo de '+name+' aplicado al proyecto';document.querySelector('#team-caption').textContent=name;document.querySelector('#team-number').textContent='0'+(Number(d.dataset.team)+1)+' / 05';pulse(im)}));
const process=document.querySelector('.process-reveal'),steps=process?[...process.querySelectorAll('li')]:[];if(process&&!reduced.matches)process.classList.add('is-enhanced');
const vr=document.querySelector('.vr-journey'),clamp=(x)=>Math.min(1,Math.max(0,x));let vrManual=null,vrManualY=0,vrPaused=false;
const vrCopy=[['De mirar un espacio.','A sentirte dentro.','Los lentes de realidad virtual abren otra manera de presentar la arquitectura de tu proyecto.'],['El proyecto se acerca.','La experiencia te rodea.','Una nueva perspectiva para descubrir la escala, la distribución y el carácter de cada ambiente.'],['Ya estás dentro.','Ahora, explóralo.','Recorre los interiores de Océano Atlántico y descubre cómo se conectan sus espacios.']];let vrChapter=-1;
function renderVR(p){if(!vr)return;const scale=1+Math.pow(clamp(p/.7),2)*3;const enter=clamp((p-.3)/.5);vr.style.setProperty('--vr-scale',reduced.matches||vrPaused?1:scale);vr.style.setProperty('--vr-person-opacity',1-clamp((p-.55)/.25));vr.style.setProperty('--vr-top',(20*(1-enter))+'%');vr.style.setProperty('--vr-side',(36*(1-enter))+'%');vr.style.setProperty('--vr-bottom',(62*(1-enter))+'%');vr.style.setProperty('--vr-radius',(80*(1-enter))+'px');vr.style.setProperty('--vr-world-opacity',clamp((p-.3)/.16));vr.style.setProperty('--vr-world-scale',1.08-.08*enter);const n=p<.32?0:p<.7?1:2;if(n!==vrChapter){vrChapter=n;vr.dataset.chapter=n;const title=document.querySelector('#vr-title');title.replaceChildren(document.createTextNode(vrCopy[n][0]),document.createElement('br'));const em=document.createElement('em');em.textContent=vrCopy[n][1];title.append(em);document.querySelector('#vr-description').textContent=vrCopy[n][2];document.querySelectorAll('[data-vr]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.vr)===n)))}}
document.querySelectorAll('[data-vr]').forEach(b=>b.addEventListener('click',()=>{vrManual=[0,.52,1][Number(b.dataset.vr)];vrManualY=scrollY;renderVR(vrManual)}));document.querySelector('.vr-motion')?.addEventListener('click',e=>{vrPaused=!vrPaused;e.currentTarget.setAttribute('aria-pressed',String(vrPaused));e.currentTarget.textContent=vrPaused?'Activar transición ▷':'Pausar transición Ⅱ';if(vrPaused){vrManual=vrChapter===2?1:0;renderVR(vrManual)}else{vrManual=null;update()}});
function update(){if(process){let active=0;steps.forEach((li,i)=>{if(li.getBoundingClientRect().top<innerHeight*.6)active=i});steps.forEach((li,i)=>{li.classList.toggle('is-current',i===active);li.classList.toggle('was-read',i<active)});document.querySelector('#process-current').textContent='0'+(active+1)}if(vr){const vrBounds=vr.getBoundingClientRect();vr.classList.toggle('is-in-view',vrBounds.top<innerHeight*.65&&vrBounds.bottom>innerHeight*.35);if(vrManual!==null&&Math.abs(scrollY-vrManualY)>120&&!vrPaused&&!reduced.matches)vrManual=null;const stopped=reduced.matches||vrPaused||document.body.classList.contains('paused');const p=vrManual!==null?vrManual:stopped?0:clamp(-vr.getBoundingClientRect().top/Math.max(1,vr.offsetHeight-innerHeight));renderVR(p)}}let pending=false;function schedule(){if(!pending){pending=true;requestAnimationFrame(()=>{pending=false;update()})}}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',schedule);new MutationObserver(schedule).observe(document.body,{attributes:true,attributeFilter:['class']});update();
})();


