(()=>{'use strict';
const reduce=matchMedia('(prefers-reduced-motion: reduce)');
const observer=new IntersectionObserver(entries=>entries.forEach(e=>e.target.classList.toggle('demo-visible',e.isIntersecting)),{threshold:.1});
window.RvisioonDemo=kind=>{
 const el=document.createElement('div');el.className='motion-demo demo-'+kind;
 const header='<div class="demo-toolbar"><b>RVISIOON <span>/ EQUIPO</span></b><i>● ● ●</i></div>';
 const foot='<small class="demo-note">VISTA ILUSTRATIVA · DATOS SIMULADOS</small>';
 if(kind==='metrics')el.innerHTML=header+'<h4>Actividad del showroom <span>Este mes ↗</span></h4><div class="demo-kpis"><div><small>VISITAS</small><b>1,462</b><em>↗ 18.4%</em></div><div><small>PROSPECTOS</small><b>48</b><em>↗ 12.2%</em></div><div><small>RESERVAS</small><b>6</b><em>Este período</em></div></div><div class="demo-chart" aria-label="Gráfico ilustrativo de actividad"><div class="demo-bars">'+[35,55,43,72,58,88,76,96,84,100,92,115].map((v,i)=>`<i style="--bar:${v}px;--delay:${-i*.3}s"></i>`).join('')+'</div><div class="demo-axis"><span>Semana 1</span><span>Semana 2</span><span>Semana 3</span><span>Semana 4</span></div></div>'+foot;
 if(kind==='units')el.innerHTML=header+'<h4>Disponibilidad <span>Vista por unidad</span></h4><div class="unit-legend"><span>● Disponible</span><span>● Reservada</span><span>● Vendida</span></div><div class="demo-unit-grid">'+Array.from({length:12},(_,i)=>`<div class="demo-unit ${i===4||i===9?'unit-changing':''}" style="--delay:${i===9?'-3s':'0s'}"><b>${201+i}</b><span class="state-available">Disponible</span>${i===4||i===9?'<span class="state-reserved">Reservada</span>':''}</div>`).join('')+'</div><p class="demo-status">Actualización de estados en una sola vista.</p>'+foot;
 if(kind==='content')el.innerHTML=header+'<h4>Estudio de contenido <span>Recursos del proyecto</span></h4><div class="demo-creative"><div class="demo-resource"><img src="assets/project-oceano.webp" alt="Recurso visual de Océano Atlántico"/><span>01 / Selecciona tu imagen</span><div class="creative-form"><b>Presentación del proyecto</b><small>Formato · Redes sociales</small><i class="creative-progress"></i></div></div><div class="demo-piece"><img src="assets/project-oceano.webp" alt="Ejemplo de pieza para redes sociales"/><div><small>OCÉANO ATLÁNTICO</small><b>Imagina tu<br/>próximo hogar.</b></div><span class="creative-ready">✓ Vista previa</span></div></div>'+foot;
 if(kind==='agenda')el.innerHTML=header+'<h4>Agenda del equipo <span>Hoy</span></h4><div class="demo-week">'+['L','M','M','J','V','S','D'].map((d,i)=>`<span class="${i===2?'chosen':''}">${d}<b>${14+i}</b></span>`).join('')+'</div><div class="demo-appointments"><div><time>10:00</time><span><b>Presentación del proyecto</b><small>Videollamada · Equipo comercial</small></span><i>Confirmada</i></div><div class="appointment-moving"><time>12:30</time><span><b>Recorrido con un prospecto</b><small>Showroom virtual · 30 minutos</small></span><i>Agendada ✓</i></div><div><time>16:00</time><span><b>Seguimiento de consulta</b><small>Información de la unidad</small></span><i>Pendiente</i></div></div>'+foot;
 observer.observe(el);return el;
};
dispatchEvent(new Event('rvisioon-demo-ready'));
const dash=document.querySelector('.dashboard-story');
if(dash){const screen=dash.querySelector('.laptop-screen');['agenda','content'].forEach((kind,i)=>{const panel=document.createElement('div');panel.className='dash-screen-panel';panel.dataset.panel=String(i+1);panel.hidden=true;panel.append(window.RvisioonDemo(kind));screen.append(panel)});const sync=()=>dash.querySelectorAll('.dash-screen-panel').forEach(p=>p.hidden=p.dataset.panel!==(dash.dataset.highlight||'0'));new MutationObserver(sync).observe(dash,{attributes:true,attributeFilter:['data-highlight']});sync();}
const range=document.querySelector('#build-range');
if(range){const section=range.closest('section'),scene=section.querySelector('.build-comparison'),output=section.querySelector('#build-state');let raf;
 const render=()=>{scene.style.setProperty('--built',range.value/100);const label=range.value<15?'Terreno actual':range.value>85?'Proyecto construido':'Visualiza la transformación';output.textContent=label;range.setAttribute('aria-valuetext',label+', '+range.value+'%');section.querySelectorAll('[data-build]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.build===range.value)));};
 range.addEventListener('input',()=>{cancelAnimationFrame(raf);render()});section.querySelectorAll('[data-build]').forEach(b=>b.addEventListener('click',()=>{cancelAnimationFrame(raf);const from=+range.value,to=+b.dataset.build,start=performance.now();const step=now=>{let p=reduce.matches?1:Math.min(1,(now-start)/800);range.value=from+(to-from)*p*p*(3-2*p);render();if(p<1)raf=requestAnimationFrame(step)};raf=requestAnimationFrame(step)}));render();}
})();
